name: rahener
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

# dependency_overrides:
#   intl: ^0.18.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  flutter_bloc: ^8.1.1
  # intl: ^0.18.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  arb_generator:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

arb_generator:
  input_filepath: "../translations.csv"
  csv_settings:
    description_index: 1
    base_index: 2
flutter:
  uses-material-design: true
  generate: true # Ad
  assets:
    - assets/data/data_en.json
    - assets/data/data_kr.json
    - assets/data/images/
