name: rahener
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  flutter_bloc: ^8.1.1
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.3
  intl_phone_number_input: ^0.7.3+1
  pin_code_fields: ^8.0.1
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.64.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3

dev_dependencies:
  arb_generator:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

arb_generator:
  input_filepath: "../translations.csv"
  csv_settings:
    description_index: 1
    base_index: 2
flutter:
  uses-material-design: true
  generate: true # Ad
  assets:
    - assets/data/data_en.json
    - assets/data/data_kr.json
    - assets/data/images/
    - assets/data/icons/
